MDScreen:
    md_bg_color: "#f7f2fa"

    MDBoxLayout:
    
        id: box
        spacing: "56dp"
        adaptive_size: True
        pos_hint: {"center_x": .9, "center_y": 0.78}

    MDTopAppBar:
        title: "Kalium Mobile V 1.0.0"
        elevation: 4
        md_bg_color:"#000000"
        pos_hint:{'center_x':0.5,'center_y':0.9}


    MDTextField:
        hint_text: "Insira o cliente"
        mode: "fill"
        pos_hint:{'center_x':0.4,'center_y':0.78}
        size_hint_x: 0.8

    